### ISSUE TITLE
set wallpaper as home not working perfect 

### ISSUE THREAD

**Issue by vitulgoyani** [pratiktimer/setWallpaperplugin#1]
here we set as wallpaper as home then it was set to both screen like at home screen and lock screen so, please solve it

**Comment by pratiktimer** [comment]
@vitulgoyani  Really Sorry For Late Response Let Me Know  If Its Working Now?

**Comment by vitulgoyani** [comment]
@pratiktimer hay, it's not work

**Comment by pratiktimer** [comment]
did u update to plugin to 0.0.4 and tried?let me know which version you are trying on?

**Comment by vitulgoyani** [comment]
yes I was updated to latest one then I was tried but it was same, is it
work with you?

**Comment by pratiktimer** [comment]
Yes I tried on Oreo....and it was working
