### ISSUE TITLE
Invalid plugin specification wallpaper.

### ISSUE THREAD

**Issue by naveenjujaray** [pratiktimer/setWallpaperplugin#16]
Invalid plugin specification wallpaper.
Invalid "plugin" specification.

this is the error i'm getting when app is about to build

**Comment by rakib205** [comment]
Same here

**Comment by naveenjujaray** [comment]
Check flutter dependencies file in your project and check the version there you'll be fine

**Comment by pratiktimer** [comment]
have updated the package check now
