### ISSUE TITLE
Home Screen Issue

### ISSUE THREAD

**Issue by YuvrajsinhDesai** [pratiktimer/setWallpaperplugin#2]
First of all, this is a good package, Lock Screen and Both(homescreen and LockScreen) this two option working perfectly but when I select only homescreen option then it sets wallpaper on both that is LockScreen and HomeScreen. I tested on Oneplus 6.

**Comment by pratiktimer** [comment]
sorry for late response yes i think that is happening for me also i will just correct that....will let you know

**Comment by YuvrajsinhDesai** [comment]
I have solved this issue by set homescreen flag in java file...

I seen that you have used Picasso... but success response from the java code is generated before actually wallpaper set on running device...so this plugin gives success message before real task is getting done.

If you have any idea to get rid of this issue which I'm facing right now then please help me it will be appreciated...😊

**Comment by pratiktimer** [comment]
great it should be something like this  
      setWallpaper(1,(String) call.arguments);
      result.success("Homescreen");

**Comment by YuvrajsinhDesai** [comment]
Thank you so much brother.😊
