### ISSUE TITLE
In setHomeLockScreen there should be FLAG_SYSTEM and FLAG_LOCK

### ISSUE THREAD

**Issue by jamrelian** [pratiktimer/setWallpaperplugin#23]
wallpaperManager.setBitmap(bitmap, null, true, WallpaperManager.FLAG_SYSTEM);

[setHomeLockScreen](https://github.com/pratiktimer/setWallpaperplugin/blob/master/android/src/main/java/com/prateektimer/wallpaper/WallpaperPlugin.java#L175)

Doesn't this only set the Home Screen wallpaper?

> Value is either 0 or a combination of FLAG_SYSTEM, and FLAG_LOCK

[WallpaperManager Docs](https://developer.android.com/reference/android/app/WallpaperManager#setBitmap(android.graphics.Bitmap,%20android.graphics.Rect,%20boolean,%20int))

**Comment by pratiktimer** [comment]
thanks for pointing. i have corrected the change in latest version 1.1.0
