### ISSUE TITLE
Error to build project after adding wallpaper plugin - SDK 28

### ISSUE THREAD

**Issue by d-apps** [pratiktimer/setWallpaperplugin#3]
Before re run the app I was trying to use the plugin.

When I was calling the method:

`await Wallpaper.homeScreen(widget.url);`

I always getting the error below:

`[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method HomeScreen on channel wallpaper).`

After "flutter clean" e run the app, I'm unable to build anymore.

**Error:**

```
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\wallpaper-0.0.6\android\src\main\java\com\prateektimer\wallpaper\WallpaperPlugin.java:7: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\wallpaper-0.0.6\android\src\main\java\com\prateektimer\wallpaper\WallpaperPlugin.java:8: error: package android.support.annotation does not exist
import android.support.annotation.RequiresApi;
                                 ^
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\wallpaper-0.0.6\android\src\main\java\com\prateektimer\wallpaper\WallpaperPlugin.java:38: error: cannot find symbol
  public void onMethodCall(@NonNull MethodCall call, @NonNull Result result) {
                            ^
  symbol:   class NonNull
  location: class WallpaperPlugin
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\wallpaper-0.0.6\android\src\main\java\com\prateektimer\wallpaper\WallpaperPlugin.java:38: error: cannot find symbol
  public void onMethodCall(@NonNull MethodCall call, @NonNull Result result) {
                                                      ^
  symbol:   class NonNull
  location: class WallpaperPlugin
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\wallpaper-0.0.6\android\src\main\java\com\prateektimer\wallpaper\WallpaperPlugin.java:65: error: cannot find symbol
        @RequiresApi(api = Build.VERSION_CODES.N)
         ^
  symbol: class RequiresApi
5 errors
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1
```

Could you please help me?

**Comment by pratiktimer** [comment]
sorry for late response the issue was i did not update to android x...........i have corrected those issues try to update 0.0.8

**Comment by d-apps** [comment]
Thanks for updating, I don't have androidX error anymore but the method is not working.

res prints = "**home screen**" but the phone wallpaper is not changed.

```
    var res;

   res = await Wallpaper.homeScreen(widget.url);

   print("RESULT: ${res.toString()}");
```

I was trying to understand where you call the method **Wallpaper.homeScreen**, because you are using invokeMethod to call it, but where it comes from?

```
  static Future<String> homeScreen(String url) async {
    final String resultvar=await _channel.invokeMethod('HomeScreen',url );
    return resultvar;
```
My java folder doesn't contain any methods about Walllpaper and MainActivity too.

![1](https://user-images.githubusercontent.com/20110433/61672197-1a372d00-acc1-11e9-9762-0f816466c61b.JPG)

**Comment by d-apps** [comment]
Other question is  does your plugin resize the picture to fit any phone screen?

**Comment by pratiktimer** [comment]
No man currently not pro developer but obviously u can do that

**Comment by pratiktimer** [comment]
You should able see inside java folder the code...inside setwallpaperplugin...

**Comment by pratiktimer** [comment]
https://github.com/pratiktimer/setWallpaperplugin/blob/master/android/src/main/java/com/prateektimer/wallpaper/WallpaperPlugin.java

**Comment by pratiktimer** [comment]
Link for crop..I will surely try in free time but if you got time you can also do it
https://www.google.com/url?sa=t&source=web&rct=j&url=https://m.youtube.com/watch%3Fv%3DhV9gY01m61Y&ved=2ahUKEwjOxvmD-cnjAhWO63MBHVvwByYQwqsBMAd6BAgHEAU&usg=AOvVaw0xFrPfJbL8sLhXWWVQhPKG

**Comment by d-apps** [comment]
> You should able see inside java folder the code...inside setwallpaperplugin...

That's strange, there's no WallpaperPlugin.java in Java Folder, I will try to copy WallpaperPlugin.java manually.

Looks like after "get packages" the plugin it's not downloading the class... 

And about the crop, I would like to just fill the screen, not crop.

I made this method but looks like it lowers the resolution that makes some wallpapers get bad quality.

I am using the package [Image](https://pub.dev/packages/image).

```
Future<Null> resizeWallpaper(dynamic path) async {

    int screenHeightInt = MediaQuery
        .of(context)
        .size
        .height
        .toInt();

    int screenWidthInt = MediaQuery
        .of(context)
        .size
        .width
        .toInt();

    print("CRIANDO UM ARQUIVO PELO DIRETÓRIO...");

    File wallpaper = File(path);

    print("LENDO A IMAGEM COMO BYTES...");

    I.Image image = I.decodeImage(wallpaper.readAsBytesSync());

    print("REDIMENSIONANDO A IMAGEM...");

    print(screenHeightInt);
    print(screenWidthInt);

    I.Image resized = I.copyResize(
        image, height: screenHeightInt, width: screenWidthInt);

    File(path)
      ..writeAsBytesSync(I.encodeJpg(resized));

    print("IMAGEM SALVA!");
    print(path);

    _setWallpaper();

  }
```

**Comment by d-apps** [comment]
Even copying your class manually, I had some import errors and I couldn't build the app. I have no ideia why it isn't downloading the java class.

**Comment by pratiktimer** [comment]
U opened in android studio?
