### ISSUE TITLE
How we can use this plugin with Dio plugin

### ISSUE THREAD

**Issue by muss01** [pratiktimer/setWallpaperplugin#4]
I need to show the user the progress bar!

**Comment by pratiktimer** [comment]
Define  Stream<String> progressString; in Stateful Widget 
call  progressString = Wallpaper.ImageDownloadProgress(iimgurl);
 progressString.listen((data) {
                            setState(() {
                              res = data;
                              downloading = true;
                            });
                            print("DataReceived: " + data);
                          }, onDone: () async {
                            lock = await Wallpaper.lockScreen();
                            setState(() {
                              downloading = false;
                              lock = lock;
                            });
                            print("Task Done");
                          }, onError: (error) {
                            setState(() {
                              downloading = false;
                            });
                            print("Some Error");
                          });

**Comment by pratiktimer** [comment]
Widget Dialog() {
    return Positioned(
      top: 200,
      left: 70,
      child: downloading
          ? Container(
              height: 120.0,
              width: 200.0,
              child: Card(
                color: Colors.black,
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    CircularProgressIndicator(),
                    SizedBox(height: 20.0),
                    Text(
                      "Downloading File : $res",
                      style: TextStyle(color: Colors.white),
                    )
                  ],
                ),
              ),
            )
          : Text(""),
    );
  }
