### ISSUE TITLE
set wallpaper as lock screen not working 

### ISSUE THREAD

**Issue by lsethi** [pratiktimer/setWallpaperplugin#5]

**Comment by lsethi** [comment]
This plug - in works sometimes for both screen option or home screen option. it is not working as expected for other image url

**Comment by lakshit1** [comment]
For me wallpaper is not setting on any screen.

**Comment by pratiktimer** [comment]
to set wallpaper only as home screen or lock screen requires api 24 or above.

**Comment by pankti16** [comment]
I am facing same problem, my minSDKVersion is 24 and it is working properly if I build and run my code. When I build apk, setting wallpaper to lock the screen is not working.

**Comment by isinghmitesh** [comment]
setting Lock screen is not working. Did anyone find solution?

**Comment by Adarsh077** [comment]
@pratiktimer Please don't close these issues without a proper solution or explanation.
I am also facing the same problem.

✅ Wallpaper.homeScreen() Works Fine
⚠ Wallpaper.lockScreen() There is some delay in this but the wallpaper is being changed.
✖ Wallpaper.bothScreen() Here Home screen works fine but the Lock screen wallpaper is not changing.
