### ISSUE TITLE
Show system setting for choosing wallpaper

### ISSUE THREAD

**Issue by lakshit1** [pratiktimer/setWallpaperplugin#6]
Can you add ACTION_CROP_AND_SET_WALLPAPER method to show setting for choosing wallpaper?
It is explained in this document https://developer.android.com/reference/android/app/WallpaperManager.html#ACTION_CROP_AND_SET_WALLPAPER

**Comment by lakshit1** [comment]
Thanks for this update. 1.0.0

**Comment by kameshkarthi** [comment]
In 1.0.0 update system screen not working? How to solve it?
